"""cascades added for card BoardAllowedUser foreign keys too

Revision ID: 12806190dddf
Revises: f986d04e71c6
Create Date: 2022-12-03 10:36:52.572027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12806190dddf'
down_revision = 'f986d04e71c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.drop_constraint('card_activity_board_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['board_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint('card_checklist_item_assigned_board_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('card_checklist_item_marked_complete_board_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['assigned_board_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['marked_complete_board_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint('card_comment_board_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['board_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('card_member_assignment_board_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['board_user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_member_assignment_board_user_id_fkey', 'board_allowed_user', ['board_user_id'], ['id'])

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_comment_board_user_id_fkey', 'board_allowed_user', ['board_user_id'], ['id'])

    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_checklist_item_marked_complete_board_user_id_fkey', 'board_allowed_user', ['marked_complete_board_user_id'], ['id'])
        batch_op.create_foreign_key('card_checklist_item_assigned_board_user_id_fkey', 'board_allowed_user', ['assigned_board_user_id'], ['id'])

    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_activity_board_user_id_fkey', 'board_allowed_user', ['board_user_id'], ['id'])

    # ### end Alembic commands ###
