"""Deleted boardactivity table

Revision ID: 202df2a0e59e
Revises: 08e080acaa4a
Create Date: 2022-12-10 10:44:57.485498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '202df2a0e59e'
down_revision = '08e080acaa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name='board_activity_board_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_user_id'], ['board_allowed_user.id'], name='board_activity_board_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='board_activity_pkey')
    )
    # ### end Alembic commands ###
