"""Entity id added to BoardActivity

Revision ID: 27321f3a384c
Revises: 12806190dddf
Create Date: 2022-12-03 17:34:12.115093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27321f3a384c'
down_revision = '12806190dddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_activity', schema=None) as batch_op:
        batch_op.drop_column('entity_id')

    # ### end Alembic commands ###
