"""created_on datetime added to Card model

Revision ID: 2da1b213c33a
Revises: 882b00b4f3a3
Create Date: 2023-02-01 07:23:13.211922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da1b213c33a'
down_revision = '882b00b4f3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default='NOW()', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
