"""checklist extended

Revision ID: 428fa5e86829
Revises: 71596b73b569
Create Date: 2022-09-05 09:12:30.215675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428fa5e86829'
down_revision = '71596b73b569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.drop_constraint('card_checklist_activity_id_fkey', type_='foreignkey')
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_complete_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('marked_complete_on', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('card_checklist_item_activity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assigned_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['marked_complete_user_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_checklist_item_activity_id_fkey', 'card_activity', ['activity_id'], ['id'])
        batch_op.drop_column('marked_complete_on')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_user_id')
        batch_op.drop_column('marked_complete_user_id')

    with op.batch_alter_table('card_checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('card_checklist_activity_id_fkey', 'card_activity', ['activity_id'], ['id'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###
