"""archived column created on user model

Revision ID: 4838bec095df
Revises: ddf121b9e65a
Create Date: 2022-12-18 10:42:17.587544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4838bec095df'
down_revision = 'ddf121b9e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
