"""empty message

Revision ID: 621551e3256d
Revises: 7c8ece8fe422
Create Date: 2022-09-16 12:38:59.569354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621551e3256d'
down_revision = '7c8ece8fe422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_allowed_user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default="0"))

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint('card_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'board_allowed_user', ['owner_id'], ['id'])

    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('board_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            'card_activity_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', [
                                    'board_user_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('board_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            'card_comment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', [
                                    'board_user_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            'card_member_assignment_activity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'card_member_assignment_activity_id_fkey', 'card_activity', ['activity_id'], ['id'])
        batch_op.drop_column('card_id')

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(),
                            autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'card_comment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('board_user_id')

    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(),
                            autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'card_activity_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('board_user_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'card_owner_id_fkey', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('board_allowed_user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
