"""full_name field removed from user, User table already has name field

Revision ID: 6b5270ecfcaa
Revises: 8103a2bda02c
Create Date: 2022-08-18 08:13:43.784907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5270ecfcaa'
down_revision = '8103a2bda02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
