"""Header colors added to BoardList

Revision ID: 6e148e8e9bf3
Revises: b3a4f89453ea
Create Date: 2023-02-06 09:04:31.472022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e148e8e9bf3'
down_revision = 'b3a4f89453ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_bgcolor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('header_textcolor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('header_textcolor')
        batch_op.drop_column('header_bgcolor')

    # ### end Alembic commands ###
