"""Card member user id replaced with board_user_id

Revision ID: 7c8ece8fe422
Revises: 5bd9b0570f47
Create Date: 2022-09-16 08:40:22.736003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8ece8fe422'
down_revision = '5bd9b0570f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('card_member_assignment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['board_user_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_member_assignment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('board_user_id')

    # ### end Alembic commands ###
