"""is_admin for BoardRole table

Revision ID: 8103a2bda02c
Revises: da4b57577025
Create Date: 2022-08-16 09:02:16.085384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8103a2bda02c'
down_revision = 'da4b57577025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_role', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
