"""CardFileUpload model created

Revision ID: 876022dbef34
Revises: 2da1b213c33a
Create Date: 2023-02-01 08:33:18.265064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876022dbef34'
down_revision = '2da1b213c33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_file_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_file_upload')
    # ### end Alembic commands ###
