"""complete column added to card_date

Revision ID: a28d6127c0bc
Revises: f4e082e04959
Create Date: 2022-10-17 08:31:22.514750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28d6127c0bc'
down_revision = 'f4e082e04959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
