"""archived fields added to card, boardlist

Revision ID: a6dcf7bd5c58
Revises: 27321f3a384c
Create Date: 2022-12-03 17:44:31.077177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dcf7bd5c58'
down_revision = '27321f3a384c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('archived_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('archived_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('archived_on')
        batch_op.drop_column('archived')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('archived_on')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
