"""empty message

Revision ID: a9b8f75b183a
Revises: f7c08a04633c
Create Date: 2022-12-03 18:24:40.383647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b8f75b183a'
down_revision = 'f7c08a04633c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint('board_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('board_allowed_user', schema=None) as batch_op:
        batch_op.drop_constraint('board_allowed_user_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('board_allowed_user_board_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('board_allowed_user_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_role', ['board_role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('board_role', schema=None) as batch_op:
        batch_op.drop_constraint('board_role_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_checklist', schema=None) as batch_op:
        batch_op.drop_constraint('card_checklist_card_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('card_checklist_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint('card_checklist_item_board_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('card_checklist_item_checklist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card_checklist', ['checklist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint('card_comment_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_constraint('card_date_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_date_board_id_fkey', 'board', ['board_id'], ['id'])

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_comment_board_id_fkey', 'board', ['board_id'], ['id'])

    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_checklist_item_checklist_id_fkey', 'card_checklist', ['checklist_id'], ['id'])
        batch_op.create_foreign_key('card_checklist_item_board_id_fkey', 'board', ['board_id'], ['id'])

    with op.batch_alter_table('card_checklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_checklist_board_id_fkey', 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key('card_checklist_card_id_fkey', 'card', ['card_id'], ['id'])

    with op.batch_alter_table('board_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('board_role_board_id_fkey', 'board', ['board_id'], ['id'])

    with op.batch_alter_table('board_allowed_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('board_allowed_user_board_id_fkey', 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key('board_allowed_user_board_role_id_fkey', 'board_role', ['board_role_id'], ['id'])
        batch_op.create_foreign_key('board_allowed_user_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('board_owner_id_fkey', 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###
