"""WIP limit on list

Revision ID: b3a4f89453ea
Revises: 876022dbef34
Create Date: 2023-02-03 08:40:09.167191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a4f89453ea'
down_revision = '876022dbef34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('wip_limit', sa.Integer(), server_default='-1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('wip_limit')

    # ### end Alembic commands ###
