"""BoardActivity created

Revision ID: d09d8579b5b7
Revises: fb11086ea346
Create Date: 2022-12-02 16:48:57.742962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09d8579b5b7'
down_revision = 'fb11086ea346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_activity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('board_user_id', sa.Integer(), nullable=False),
                    sa.Column('activity_on', sa.DateTime(), nullable=True),
                    sa.Column('event', sa.Text(), nullable=False),
                    sa.Column('changes', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['board_id'], ['board.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['board_user_id'], ['board_allowed_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_activity')
    # ### end Alembic commands ###
