"""archived_by_list column added to card

Revision ID: ddf121b9e65a
Revises: 202df2a0e59e
Create Date: 2022-12-16 11:34:00.054958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf121b9e65a'
down_revision = '202df2a0e59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_by_list', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('archived_by_list')

    # ### end Alembic commands ###
