"""Changed Checklist marked user id and assigned user id to board user

Revision ID: e144d6633b00
Revises: 621551e3256d
Create Date: 2022-09-16 14:17:50.241169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e144d6633b00'
down_revision = '621551e3256d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_complete_board_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_board_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('card_checklist_item_marked_complete_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('card_checklist_item_assigned_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_allowed_user', ['assigned_board_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'board_allowed_user', ['marked_complete_board_user_id'], ['id'])
        batch_op.drop_column('marked_complete_user_id')
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marked_complete_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_checklist_item_assigned_user_id_fkey', 'user', ['assigned_user_id'], ['id'])
        batch_op.create_foreign_key('card_checklist_item_marked_complete_user_id_fkey', 'user', ['marked_complete_user_id'], ['id'])
        batch_op.drop_column('assigned_board_user_id')
        batch_op.drop_column('marked_complete_board_user_id')

    # ### end Alembic commands ###
