"""List background color, text color added

Revision ID: e56e0ed57e72
Revises: 6e148e8e9bf3
Create Date: 2023-02-06 09:32:13.613844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56e0ed57e72'
down_revision = '6e148e8e9bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_bgcolor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('list_textcolor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('list_textcolor')
        batch_op.drop_column('list_bgcolor')

    # ### end Alembic commands ###
