"""remove is_due_date from card date

Revision ID: f3351989340c
Revises: a28d6127c0bc
Create Date: 2022-10-19 08:50:21.882611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3351989340c'
down_revision = 'a28d6127c0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_column('is_due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_due_date', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
