"""empty message

Revision ID: f4e082e04959
Revises: f765b4683c16
Create Date: 2022-10-15 13:15:03.005033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4e082e04959'
down_revision = 'f765b4683c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.alter_column('dt_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('dt_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.alter_column('dt_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('dt_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
