"""Board archive fields

Revision ID: f986d04e71c6
Revises: d09d8579b5b7
Create Date: 2022-12-03 10:11:07.358995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f986d04e71c6'
down_revision = 'd09d8579b5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('archived_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('archived_on')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
