"""cascades added to card models

Revision ID: fb11086ea346
Revises: f3351989340c
Create Date: 2022-11-17 08:38:48.179624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb11086ea346'
down_revision = 'f3351989340c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint('card_list_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'list', ['list_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.drop_constraint('card_activity_card_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint('card_comment_activity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card_activity', ['activity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_constraint('card_date_card_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('card_member_assignment_card_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_member_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_member_assignment_card_id_fkey', 'card', ['card_id'], ['id'])

    with op.batch_alter_table('card_date', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_date_card_id_fkey', 'card', ['card_id'], ['id'])

    with op.batch_alter_table('card_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_comment_activity_id_fkey', 'card_activity', ['activity_id'], ['id'])

    with op.batch_alter_table('card_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_activity_card_id_fkey', 'card', ['card_id'], ['id'])

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_list_id_fkey', 'list', ['list_id'], ['id'])

    # ### end Alembic commands ###
